sahm/urls.py
from django.conf.urls import url
from . import views

app_name = 'sahm'
urlpatterns = [
    url(r'^$', views.tela_inicial, name='index'),
    url(r'^sobre/$', views.sobre, name='sobre'),
    url(r'^como_funciona/$', views.horario, name='horario'),
    url(r'^contate-nos/$', views.contato, name='contato'),
    url(r'^login/$', views.monitor_login, name='login'),
    url(r'^cadastro/$', views.cadastrar_monitor, name='cadastrar_monitor'),
    url(r'^monitoria_cadastro/$', views.cadastro_monitoria, name='cadastro_monitoria'),
    url(r'^monitoria/$', views.feed_monitoria, name='feed_monitoria'),
    url(r'^acesso/$', views.acesso_monitor, name="acesso_monitor"),
    url(r'^logout/$', views.monitor_logout, name="logout"),
    url(r'^dados_cadastrais_monitor/$', views.dados_cadastrais_monitor, name='dados_cadastrais_monitor'),
    url(r'^dados_principal_monitor/$', views.dados_principal_monitor, name='dados_principal_monitor'),
    url(r'^mudar_senha/$', views.update_password, name='update_password'),
    url(r'^mudar_email/$', views.update_email, name='update_email'),
    url(r'^excluir_conta/$', views.excluir_conta, name='excluir_conta'),
]

site_sahm/site_sahm/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

site_sahm/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include('sahm.urls', namespace='sahm')),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <title>S.A.H.M</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style></style>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">
    <script src="{% static 'js/cadastrojs.js' %}" type="text/javascript"></script>


    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <style>
      /* Remove the navbar's default margin-bottom and rounded borders */
      .navbar {
        margin-bottom: 0;
        border-radius: 0;
      }

      /* Add a gray background color and some padding to the footer */
      /* Rodape*/

  		footer#rodape {

  			color:#777;
  			background-color: black;
      	padding: 25px;
  			font-weight: bold;
  			width: 100.9%;
  			margin-left: -15px;
  			margin-bottom: -15px;

  		}

  		footer#rodape ul {

  			list-style: none;
  			text-align: center;
  			margin-bottom: 5px;
  			margin-right: 40px;
  		}

  		footer#rodape p {
  			text-align: center;
  			margin-bottom: -5px;
  		}

  		footer#rodape a {

  			color:#777;
  			text-decoration: none;
  		}

  		footer#rodape a:hover{
  			color: white;
  		}

  	  .carousel-inner img {
  	      width: 100%; /* Set width to 100% */
  	      margin: auto;
  	      min-height:200px;
  	  }

  	  /* Hide the carousel text when the screen is less than 600 pixels wide */
  	  @media (max-width: 600px) {
  	    .carousel-caption {
  	      display: none;
  	    }

  	    img#img01 {
  	    	/*width: 20%;*/
  	    }
    }
    </style>

  </head>
  <body>
     <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">

            <button type="button" class="navbar-toggle collapsed" data-toggle="collapsed" data-target="#navbar">

              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'sahm:index' %}">S.A.H.M</a>
          </div>

          <div id="navbar" class="navbar-collapse collapsed">
            <ul class="nav navbar-nav navbar-right">

              <li class="active"><a href="{% url 'sahm:index' %}">Home <span class="sr-only">(current)</span></a></li>
              <li><a href="{% url 'sahm:horario' %}">Horários</a></li>
              <li><a href="{% url 'sahm:sobre' %}">Sobre</a></li>
              <li><a href="{% url 'sahm:contato' %}">Contato</a></li>
              <li><a href="{% url 'sahm:login' %}"><img src="{% static 'Imagens/login4.png' %}"> Entre</a></li>
            </ul>
          </div>
        </div>
      </nav>
      <div class="container">
        <div class="row">
          <div role="main">
            <div class="info">
              {% block content %}
              {% endblock %}
            </div>
          </div>
        </div>
      </div>

      <footer class="container" id="rodape">
        <div class="container text-center">
          <div class="row">
            <div class="col-sm-4">
              <a href="{% url 'sahm:index' %}"><h4>S.A.H.M</h4></a>
              <ul>
                <a href="{% url 'sahm:sobre' %}"><li>Sobre</li></a>
                <a href="{% url 'sahm:horario' %}"><li>Horários</li></a>
                <a href="{% url 'sahm:contato' %}"><li>Contato</li></a>
                <a href="{% url 'sahm:cadastrar_monitor' %}"><li>Cadastre-se</li></a>
              </ul>
            </div>

            <div class="col-sm-4">
              <h4>Informações Adicionais</h4>
              <p>Rua Cícero Eduardo, S/N - Bairro Junco - Picos/PI<br></p><p><span id="fone">Fone: (89) 9 9927-5764</span></p>
              <p>@Copyright 2017 - by Majuca S.A</p>
            </div>

            <div class="col-sm-4">
              <h4>Siga-nos</h4>
              <ul>
                <a href="https://www.facebook.com/" target="black"><li><img src="{% static 'Imagens/facebook.jpg' %}" style="width: 10%"></li></a>
                <a href="https://twitter.com/" target="black"><li><img src="{% static 'Imagens/twitter.png' %}" style="width: 10%"></li></a>
                <a href="https://www.linkedin.com/?originalSubdomain=br" target="black"><li><img src=" {% static 'Imagens/linkedin.png' %}" style="width: 11%"></li></a>
                <a href="https://plus.google.com" target="black"><li><img src="{% static 'Imagens/google.jpg' %}" style="width: 12%"></li></a>
              </ul>
            </div>
          </div>
        </div>
      </footer>

  	<script src="{% static 'js/jquery.min.js' %}"></script>
  	<script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/validator.js' %}"></script>
    <script src="{% static 'js/curso.js' %}"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js"></script>

  </body>
</html>

templates/contato.html
{% extends 'base.html' %}

{% block content %}

  <form method="POST" action="" role="form" name="cad" onsubmit="return validar()">{% csrf_token %}

            <h3>Formulário de Contato</h3>
  					<div class="row">
              <div class="form-group col-md-12">
    					  <label for="nome" class="control-label">Nome: </label>
    						<input id="nome" type="text" name="nome" placeholder="Informe o seu nome completo" class="form-control" required=""/>
              </div>
            </div>

            <div class="row">
              <div class="form-group col-md-12">
                <label for="email" class="control-label">E-mail: </label>
    						<input type="email" name="Email" id="email" placeholder="Informe o seu email" class="form-control" required=""/>
              </div>
            </div>

            <div class="row">
              <div class="form-group col-md-12">
  						  <label for="data" class="control-label">Data de Nascimento: </label>
  						  <input type="text" name="data" id="data" placeholder="dd/mm/aaaa" class="form-control" required=""/>
              </div>
            </div>

            <div class="row">
              <div class="form-group col-md-12">
  					    <label for="msg" class="control-label">Mensagem: </label>
  						  <textarea class="form-control" name="mensagem" id="msg" cols="80" rows="8" placeholder="Escreva aqui sua mensagem" required=""></textarea>
              </div>
            </div>

            <div class="row" id="actions">
              <input type="submit" placeholder="Enviar mensagem" class="btn btn-default">
  						<input type="reset" value="Limpar dados" class="btn btn-default">
            </div>
  </form>

{% endblock %}

templates/funcionamento.html
{% extends 'base.html' %}

{% block content %}

{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}

<div class="container-fluid text-center">
  <div class="row">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
          <!--<div class="item">
            <img src="static/Imagens/socio.jpg" alt="Image">
            <div class="carousel-caption">
              <h1>Deseja que o seu negócio na T.I cresca ?</h1>
              <h3>Contrate os freelancers com as mais diversas habilidades e experiências.</h3>
            </div>
          </div>-->

          <div class="item active">
            <img src="static/Imagens/freelancer.jpg" alt="Image">
            <div class="carousel-caption">
              <!--<h1>E aí parça deseja ganhar uma graninha a mais ?</h1>
              <h3>Cadastre-se e tenha acesso aos projetos com os mais variados preços e necessidades. Aumente já o seu networking e experiência.</h3>-->
            </div>
          </div>
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
    </div>
  </div>

  <div class="row">
    <h3>O que você pode fazer?</h3><br>
      <div class="col-sm-4">
        <!--<img src="static/Imagens/projeto.jpg" class="img-responsive" alt="Image">-->
        <p>Cadastre-se no site e marque os seus horários para a monitoria.</p>
      </div>
      <div class="col-sm-4">
        <!--<img src="static/Imagens/feedFrela.jpeg" class="img-responsive" alt="Image">-->
        <p>Visualize as monitorias e o monitor responsável pelas matérias.</p>
      </div>
  </div>

  <div class="row">
  	<h3>Como funciona?</h3>
  		<div class="col-sm-4">
  			<!--<img src="static/Imagens/projeto.png" class="img-responsive" alt="Image">-->
  			<p>Cadastre e especifique as informações de data, hora e local de sua monitoria.</p>
  		</div>
  		<div class="col-sm-4">
  			<!--<img src="static/Imagens/pesquisa.png" class="img-responsive" alt="Image">-->
  			<p>Encontre as monitorias já cadastradas.</p>
  		</div>
  		<div class="col-sm-4">
  			<!--<img src="static/Imagens/trabalho.jpg" class="img-responsive" alt="Image">-->
  			<p>Visualize as informações de contato do monitor.</p>
  		</div>
  </div>

</div>

{% endblock %}

templates/sobre.html
{% extends 'base.html' %}

{% block content %}

<div class="container text-center">
	<div class="row" style="margin-top: 5%">

		<div class="col-sm-4">
			<h3>Objetivo do Projeto</h3>
			<div class="well">
				<p class="sobre">

					O S.A.H.M (Sistema de Agendamento de Horários de Monitoria) é um projeto que tem como objetivo prestar serviços de agendamento e cadastro de horários de monitoria para os discentes
					da Universidade Federal do Piauí, mas precisamente do campus Senador Helvidio Nunes de Barros, através do cadastro de monitores, na qual os mesmos cadastram os seus horários para atendimento
					aos discentes da sua matéria, na qual é monitor. Sendo que essas informações posteriormente serão visualizadas pela comunidade acadêmica</p>
			</div>
		</div>

		<div class="col-sm-4">
			<h3>Nossa Missão</h3>
			<div class="well">
				<p class="sobre">
					A empresa tem como missão difundir e tornar ainda mais visível aos usuários e monitores as datas e horários de monitorias, a fim de servir como uma ferramenta de auxilio desta atividade acadêmica,
					através de uma plataforma de visualização de datas e horarios, que facilite o acesso à essas informações, tornado assim uma aplicação prática que gere sintonia entre monitores e discentes</p>
			</div>
		</div>
	</div>
</div>

{% endblock %}

templates/viewMonitor.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <title>Sua Conta</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style></style>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>
  <body>
     <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">

            <button type="button" class="navbar-toggle collapsed" data-toggle="collapsed" data-target="#navbar">

              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">S.A.H.M</a>
          </div>

          <div id="navbar" class="navbar-collapse collapsed">
            <ul class="nav navbar-nav navbar-right">

              <li class="active"><a href="#">Home <span class="sr-only">(current)</span></a></li>
              <li><a href="#">Horários</a></li>
              <li><a href="#">Sobre</a></li>
              <li><a href="#">Contato</a></li>
              <li><a href="{% url 'sahm:logout' %}"><img src="{% static 'Imagens/login4.png' %}"> Entre</a></li>
            </ul>
          </div>
        </div>
      </nav>

      <div class="container-fluid">
        <div class="row">
          <div role="main">
            <div class="container-fluid">


              <div class="row">

                <div class="col-md-3">
                  <div class="navbar" role="navigation">
                    <div id="navbar" class="navbar-collapse collapsed">
                      <ul class="nav">
                        <li><img src="{% static 'Imagens/images.png' %}"  alt="Logo Da Conta"/></li>
                        <li><a href="{% url 'sahm:acesso_monitor' %}">Inicio</a></li>
                        <li><a href="{% url 'sahm:feed_monitoria' %}">Monitorias</a></li>
                        <li><a href="{% url 'sahm:dados_cadastrais_monitor' %}">Atualizar Informações Cadastrais</a></li>
                        <li><a href="{% url 'sahm:dados_principal_monitor' %}">Configurações de Monitor</a></li>
                        <li><a href="{% url 'sahm:logout' %}">Sair</a></li>
                      </ul>
                    </div>
                  </div>
                </div>

                <div class="col-md-9">

                  <form id="formCad" data-toggle="validator" role="form" method="POST">
                    {% csrf_token %}

                      {% block content %}
                      {% endblock %}
                  </form>
                </div>

            </div>
          </div>
        </div>
      </div>

      <footer class="row">

      </footer>
    </div>


  	<script src="{% static 'js/jquery.min.js' %}"></script>
  	<script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/validator.js' %}"></script>
    <script src="{% static 'js/curso.js' %}"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js"></script>
  </body>
</html>