sahm/urls.py
from django.conf.urls import url
from . import views

app_name = 'sahm'
urlpatterns = [
    url(r'^$', views.tela_inicial, name='index'),
    url(r'^sobre/$', views.sobre, name='sobre'),
    url(r'^como_funciona/$', views.horario, name='horario'),
    url(r'^contate-nos/$', views.contato, name='contato'),
    url(r'^login/$', views.monitor_login, name='login'),
    url(r'^cadastro/$', views.cadastrar_monitor, name='cadastrar_monitor'),
    url(r'^monitoria_cadastro/$', views.cadastro_monitoria, name='cadastro_monitoria'),
    url(r'^monitoria/$', views.feed_monitoria, name='feed_monitoria'),
    url(r'^acesso/$', views.acesso_monitor, name="acesso_monitor"),
    url(r'^logout/$', views.monitor_logout, name="logout"),
    url(r'^dados_cadastrais_monitor/$', views.dados_cadastrais_monitor, name='dados_cadastrais_monitor'),
    url(r'^dados_principal_monitor/$', views.dados_principal_monitor, name='dados_principal_monitor'),
    url(r'^mudar_senha/$', views.update_password, name='update_password'),
    url(r'^mudar_email/$', views.update_email, name='update_email'),
    url(r'^excluir_conta/$', views.excluir_conta, name='excluir_conta'),
]

site_sahm/site_sahm/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

site_sahm/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include('sahm.urls', namespace='sahm')),
]

sahm/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.exceptions import ValidationError


# Create your models here.

class Monitor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, unique=True)
    #nome = models.CharField(max_length=250)
    #matricula = models.BigIntegerField()
    #email = models.EmailField()
    telefone = models.BigIntegerField(null=True, blank=True)
    curso = models.CharField(max_length=200, null=True, blank=True)
    materia =  models.CharField(max_length=200, null=True, blank=True)
    nascimento = models.DateField(null=True, blank=True)
    #senha = models.CharField(max_length=200)

    def __str__(self):
        return str(self.user)

        @receiver(post_save, sender=User)
        def criar_monitor(sender, instance, created, **kwargs):
            if created:
                Monitor.objects.create(user=instance)

        @receiver(post_save, sender=User)
        def salvar_monitor(sender, instance, **kwargs):
            instance.monitor.save()

class Monitoria(models.Model):
    #user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='monitoria')
    dia = models.DateField(u'Dia da Monitoria', help_text=u'Dia da Monitoria', null=True, blank=True)
    hora_inicio = models.TimeField(u'Hora de Inicio', help_text=u'Hora de Inicio', null=True, blank=True)
    hora_termino = models.TimeField(u'Hora de Termino', help_text=u'Hora de Termino', null=True, blank=True)
    sala = models.IntegerField(null=True, blank=True)

    def check_overlap(self, hora_inicio, hora_termino, novo_inicio, novo_fim):
        overlap = False

        if novo_inicio == hora_termino or novo_fim == hora_inicio:
            overlap = False
        elif (novo_inicio >= hora_inicio and novo_inicio <= hora_termino) or (novo_fim >= hora_inicio and novo_fim <= hora_termino): #innner limits
            overlap = True
        elif novo_inicio <= hora_inicio and novo_fim >= hora_termino:
            overlap = True

        return overlap

    def clean (self):
        if self.hora_termino <= self.hora_inicio:
            raise ValidationError('Tempo de término menor que o Tempo de inicio.')

        #events = Monitoria.objects.filter(dia=self.dia)
        #if events.exists():
            #if self.check_overlap(events.hora_inicio, events.hora_termino, self.hora_inicio, self.hora_termino):
                #raise ValidationError('There is an overlap with another event: ' + str(events.dia) + ', ' + str(events.hora_inicio) + '-' + str(events.hora_termino))

    def __str__(self):
        return str(self.user)

    #@receiver(post_save, sender=User)
    #def criar_monitoria(sender, instance, created, **kwargs):
    #    if created:
    #        Monitoria.objects.create(user=instance)

    #@receiver(post_save, sender=User)
    #def salvar_monitoria(sender, instance, **kwargs):
    #    instance.monitoria.save()

sahm/views.py
from django.shortcuts import render, redirect
from .models import Monitor
from .models import Monitoria
from .forms import UserModelForm
from .forms import MonitorModelForm
from .forms import MonitoriaModelForm
#from .forms import EmailUpdateModelForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.http import HttpResponseRedirect
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from datetime import date
from datetime import datetime

#from django.contrib.auth.hashers


# Create your views here.

def tela_inicial(request):
    return render(request, 'index.html')

def sobre(request):
    return render(request, 'sobre.html')

def horario(request):
    return render(request, 'funcionamento.html')

def contato(request):
    return render(request, 'contato.html')

def cadastrar_monitor(request):

    form = UserModelForm(request.POST or None)
    if request.method == "POST":
        #form_monitor = MonitorModelForm(request.POST or None)

        if form.is_valid():

            try:
                monitor_username = User.objects.get(username=request.POST.get('matricula'))
                context = {
                    'form':form,
                    'msg_matricula': 'Matricula já cadastrada!'
                }
                return render(request, 'sahm/cadastroMonitor.html', context)

            except User.DoesNotExist:
                monitor_email = User.objects.filter(email=request.POST.get('email')).count()
                if monitor_email:
                    context = {
                        'form':form,
                        'msg_email': 'Email já cadastrado!'
                    }
                    return render(request, 'sahm/cadastroMonitor.html', context)
                else:

                    user = form.save(commit=False)
                    username = form.cleaned_data['username']
                    password = form.cleaned_data['password']
                    user.set_password(password)
                    user.save()
                    return render(request, 'sahm/login.html')
    else:
        form = UserModelForm()

    context = {'form':form}
    return render(request, 'sahm/cadastroMonitor.html', context)

def monitor_login(request):

    if request.method == "POST":

        try:
            monitor_consulta = User.objects.get(email=request.POST.get('email'))
            monitor = authenticate(username=monitor_consulta.username, password=request.POST.get('password'))

            if monitor is not None:
                if monitor.is_active:
                    login(request, monitor)
                    return HttpResponseRedirect('/acesso', {'monitor':monitor_consulta})
            else:
                return render(request, 'sahm/login.html', {'msg':'Senha inválida!'})
        except User.DoesNotExist:
            return render(request, 'sahm/login.html', {'msg':'Conta inexistente!'})

    return render(request, 'sahm/login.html')

@login_required
def monitor_logout(request):
    logout(request)
    return render(request, 'sahm/login.html', {})

@login_required
def acesso_monitor(request):
    return render(request, 'viewMonitor.html')

@login_required
def cadastro_monitoria(request):

    user = User.objects.get(username=request.user.username)
    #form = MonitoriaModelForm(request.POST or None,  initial={'dia': user.monitoria.dia, 'sala':user.monitoria.sala,'hora_inicio': user.monitoria.hora_inicio, 'hora_termino':user.monitoria.hora_termino}, prefix="monitr")

    try:
        if user.monitor.materia:
            if request.method == "POST":
                form = MonitoriaModelForm(request.POST or None)
                if form.is_valid():

                    sala_cad = form.cleaned_data.get('sala')
                    dia_cad = form.cleaned_data.get('dia')
                    hora_inicio_cad = form.cleaned_data.get('hora_inicio')
                    hora_termino_cad = form.cleaned_data.get('hora_termino')

                    now = date.today()
                    data = datetime.strptime(str(dia_cad), "%Y-%m-%d").date()
                    tempo = datetime.strptime(str(hora_inicio_cad), "%H:%M:%S").time()
                    
                    if data < now or data.year > now.year:
                        return render(request, 'sahm/monitoria.html', {'msg2':'Informe uma Data no Tempo Certo!', 'form':form})

                    check_sala = Monitoria.objects.filter(sala=sala_cad, dia=dia_cad, hora_inicio=hora_inicio_cad)

                    if check_sala.exists():
                        return render(request, 'sahm/monitoria.html', {'msg2':'Monitoria Já cadastrada nesse horário!', 'form':form})

                    try:
                        check_horario = Monitoria.objects.get(sala=sala_cad, dia=dia_cad)

                        if check_horario:
                            if tempo >= check_horario.hora_inicio and tempo < check_horario.hora_termino:
                                return render(request, 'sahm/monitoria.html', {'msg2':'Monitoria Já cadastrada nesse intervalo!', 'form':form})

                    except Monitoria.DoesNotExist:
                        monitoria = form.save(commit=False)
                        monitoria.user = user
                        monitoria.dia = form.cleaned_data.get('dia')
                        monitoria.sala = form.cleaned_data.get('sala')
                        monitoria.hora_inicio = form.cleaned_data.get('hora_inicio')
                        monitoria.hora_termino = form.cleaned_data.get('hora_termino')
                        monitoria.save()

                    monitoria = form.save(commit=False)
                    monitoria.user = user
                    monitoria.dia = form.cleaned_data.get('dia')
                    monitoria.sala = form.cleaned_data.get('sala')
                    monitoria.hora_inicio = form.cleaned_data.get('hora_inicio')
                    monitoria.hora_termino = form.cleaned_data.get('hora_termino')
                    monitoria.save()

                    #user.save()
                    context = {'form':monitoria, 'msgOk':'Monitoria cadastrada com sucesso!','user':user}
                    return render(request, 'sahm/monitoria.html', context)
                else:
                    return render(request, 'sahm/monitoria.html', {'msg2':'Os horários estão incorretos!','form':form})

            else:
                form = MonitoriaModelForm()
                return render(request, 'sahm/monitoria.html', {'form':form})
        else:
            return render(request, 'sahm/monitoria.html', {'msg':'Para prosseguir informe a matéria!'})
    except User.monitor.RelatedObjectDoesNotExist:
        return render(request, 'sahm/monitoria.html', {'msg':'Para prosseguir informe a matéria!'})

@login_required
def dados_cadastrais_monitor(request):

    user = User.objects.get(username= request.user.username)

    try:

        monitor = Monitor.objects.get(user=user)

        #try:

            #form_monitor = MonitorModelForm(request.POST or None, initial={'telefone': user.monitor.telefone, 'nascimento':user.monitor.nascimento,'curso': user.monitor.curso, 'materia':user.monitor.materia}, prefix="moni")

        #except User.monitor.RelatedObjectDoesNotExist:
            #form_monitor = MonitorModelForm(request.POST or None)

        if request.method == "POST":
            #form_monitor = MonitorModelForm(request.POST or None, initial={'telefone':user.monitor.telefone, 'nascimento':user.monitor.nascimento, 'curso': user.monitor.curso, 'materia':user.monitor.materia}, prefix="moni")
            form_monitor = MonitorModelForm(request.POST or None, instance=monitor)
            if form_monitor.is_valid():
                if request.user.is_authenticated:

                    if request.POST['nome'] != '':
                        user.first_name = request.POST['nome']

                    #monitor = form_monitor.save(commit=False)
                    ##user.monitor = monitor
                    #user.save()
                    monitor = form_monitor.save(commit=False)
                    monitor.user = user
                    monitor.telefone = form_monitor.cleaned_data.get('telefone')
                    monitor.nascimento = form_monitor.cleaned_data.get('nascimento')
                    monitor.curso = form_monitor.cleaned_data.get('curso')
                    monitor.materia = form_monitor.cleaned_data.get('materia')
                    monitor.save()
                    context = {'form_monitor':monitor, 'user':user, 'msg':'Dados alterados com sucesso!'}
                    return render(request, 'sahm/updateMonitor.html', context)

                else:
                    return redirect('/acesso')

            else:
                return redirect('/acesso')
        else:
            form_monitor = MonitorModelForm(instance=monitor)
            context = {'form_monitor':form_monitor, 'user':user}
            return render(request, 'sahm/updateMonitor.html', context)

    except Monitor.DoesNotExist:

        if request.method == "POST":
            #form_monitor = MonitorModelForm(request.POST or None, initial={'telefone':user.monitor.telefone, 'nascimento':user.monitor.nascimento, 'curso': user.monitor.curso, 'materia':user.monitor.materia}, prefix="moni")
            form_monitor = MonitorModelForm(request.POST or None)
            if form_monitor.is_valid():
                if request.user.is_authenticated:

                    if request.POST['nome'] != '':
                        user.first_name = request.POST['nome']

                    #monitor = form_monitor.save(commit=False)
                    ##user.monitor = monitor
                    #user.save()

sahm/templates/sahm/cadastroMonitor.html
{% extends 'base.html' %}

{% block content %}
<h1 class="page-header"> Cadastre os seus dados</h1>

<form id="formCadCliente" data-toggle="validator" role="form" method="POST" action="{% url 'sahm:cadastrar_monitor' %}">{% csrf_token %}

  <div class="row">
    <div class="form-group col-md-12">
      <label for="id_nome" class="control-label">Nome:</label>
      <!--<input type="text" name="nome" placeholder="Informe o seu nome completo" id="id_nome" class="form-control" required/>-->
      {{form.first_name}}
      <div class="help-block with-errors"></div>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-8">
      <label for="id_email" class="control-label">Email:</label>
      <!--<input type="email" name="email" id="id_email" class="form-control" data-error="Por favor, informe um e-mail correto." required/>-->
      {{form.email}}
      <div class="help-block with-errors">{{msg_email}}</div>
    </div>

    <div class="form-group col-md-4">
      <label for="id_matricula" class="control-label">Matrícula:</label>
      <!--<input type="number" name="matricula" id="id_matricula" class="form-control" required/>-->
      {{form.username}}
      <div class="help-block with-errors">{{msg_matricula}}</div>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-6">
      <label for="id_senha" class="control-label">Senha:</label>
      <!--<input type="password" name="senha" id="id_senha" class="form-control" data-minlength="6" required/>-->
      {{form.password}}
      <span class="help-block">Mínimo de seis (6) digitos</span>
    </div>

    <div class="form-group col-md-6">
      <label for="id_conf_senha" class="control-label">Confirme a senha:</label>
      <input type="password" name="confirmaSenha" id="id_conf_senha" class="form-control" data-match="#id_senha" data-match-error="As senhas não conferem!." required/>
      <div class="help-block with-errors"></div>
    </div>
  </div>
  <!--{% if msg_confirm %}
    <h4>{{msg_confirm}}</h4>
  {% endif%}-->
  <div class="row" id="actions">
    <button type="submit" class="btn btn-primary">Cadastrar</button>
    <a href="{% url 'sahm:login' %}" class="btn btn-default">Cancelar</a>
  </div>

</form>
{% endblock %}

sahm/templates/sahm/feedMonitoria.html
{% extends 'viewMonitor.html' %}

{% block content %}

<div class="info">
  <h2 class="page-header">Monitorias Cadastradas</h2>
</div>

{% endblock %}

sahm/templates/sahm/login.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block content %}

<img src="{% static 'Imagens/images.png' %}"  alt="Logo De Identificacao">
<h1 class="page-header">Informe suas credenciais</h1>

<form id="formLogin" data-toggle="validator" role="form" action="{% url 'sahm:login' %}" method="POST">{% csrf_token %}
  <div class="form-group">
    <label for="id_login" class="control-label">Email: </label>
    <input type="text" name="email" placeholder="Informe o seu email" id="id_login" class="form-control" required>
    <!--{{form.email}}-->
    <div class="help-block with-errors"></div>

  </div>

  <div class="form-group">
    <label for="id_senha" class="control-label">Senha: </label>
    <input type="password" name="password" id="id_senha" class="form-control" required>
    <!--{{form.password}}-->
    <div class="help-block with-errors"></div>
  </div>

  {% if msg %}
    <h4>{{msg}}</h4>
  {% endif%}

  <button type="submit" class="btn btn-primary">Acessar</button>
</form>

<div class="row2">
  <a href="{% url 'sahm:cadastrar_monitor' %}">Não é cadastrado? Cadastre-se</a>
</div>

{% endblock %}

sahm/templates/sahm/monitoria.html
{% extends 'viewMonitor.html' %}

{% block content %}

<div class="info">
  <h2 class="page-header">Cadastrar Monitorias</h2>
</div>

{% if msg %}
  <h4>{{msg}}</h4>
{% else %}
<form class="form-horizontal" data-toggle="validator" role="form" method="POST" action="{% url 'sahm:acesso_monitor' %}">{% csrf_token %}
    <fieldset>

        <!-- Text input-->
        <div class="row">
          <div class="form-group">
              <label class="col-md-3 control-label" for="id_sala">Local:</label>
              <div class="col-md-2">
                  <!--<input id="sala_monitoria" name="sala" type="text" placeholder="Nº da Sala" class="form-control input-md" required="">-->
                {{form.sala}}
                <div class="help-block with-errors"></div>
              </div>
          </div>
        </div>

        <!-- Appended Input-->
        <div class="row">
          <div class="form-group">
              <label class="col-md-3 control-label" for="id_dia">Dia da Monitoria:</label>
              <div class="col-md-4">
                  <div class="input-group">
                      <!--<input id="eventDate" name="eventDate" class="form-control" placeholder="DD/MM/YYYY" type="date" required="">-->
                      {{form.dia}}
                      <div class="help-block with-errors"></div>
                  </div>

              </div>
          </div>
        </div>
        <!-- Text input-->
        <div class="row">
          <div class="form-group">
              <label class="col-md-3 control-label" for="id_hora_inicio">Horário de Início:</label>
              <div class="col-md-3">
                  <!--<input id="id_hora_inicio" name="venueName" type="time" placeholder="" class="form-control input-md">-->
                  {{form.hora_inicio}}
                  <div class="help-block with-errors"></div>
              </div>
          </div>
        </div>

        <div class="row">
          <div class="form-group">
              <label class="col-md-3 control-label" for="id_hora_termino">Horário de Término:</label>
              <div class="col-md-3">
                  <!--<input id="id_hora_termino" name="hora_termino" type="time"  class="form-control input-md">-->
                  {{form.hora_termino}}
                  <div class="help-block with-errors"></div>
              </div>
          </div>
        </div>

        {% if msg2 %}
          <h4> {{msg2}} </h4>
        {% endif %}

        {% if msgOk %}
          <h4>{{msgOk}}</h4>
        {% else %}
        <!-- Button (Double) -->
          <div class="row">
            <div class="form-group">
                <label class="col-md-1 control-label" for="submitButton"></label>
                <div class="col-md-8">
                    <button id="submitButton" name="submitButton" class="btn btn-primary">Salvar Monitoria</button>
                    <a href="{% url 'sahm:acesso_monitor' %}" class="btn btn-default">Cancelar</a>
                </div>
            </div>
          </div>
        {% endif %}
    </fieldset>
</form>
{% endif %}
{% endblock %}

sahm/templates/sahm/updateEmail.html
{% extends 'viewMonitor.html' %}

{% block content %}

<div class="info">
  <h3 class="page-header">Atualize seu Novo Email</h3>
</div>

<form id="formUpdatePass" data-toggle="validator" role="form" method="POST" action="{% url 'sahm:update_email' %}">{% csrf_token %}

<div class="container-fluid">
  <div class="row">
    <div class="form-group col-md-4">
      <label class="control-label">Email antigo:</label>
      {{user.email}}
    </div>

    <div class="form_group col-md-4">
      <label for="id_email" class="control-label">Email novo:</label>
      <input type="email" name="email" id="id_email" class="form-control" data-error="Por favor, informe um e-mail correto." required/>
    </div>
  </div>

  <div class="row">

    <div class="form_group col-md-5">
      <label for="id_senha" class="control-label">Informe a sua senha:</label>
      <input type="password" name="password" id="id_senha" class="form-control" data-minlength="6" required/>
    </div>
  </div>

  {% if msg %}
    <h4>{{msg}}</h4>
  {% endif %}

  <div class="row" id="actions">
    <button type="submit" class="btn btn-primary">Alterar Email</button>
    <a href="{% url 'sahm:dados_principal_monitor' %}" class="btn btn-default">Cancelar</a>
  </div>
</div>
</form>
{% endblock %}

sahm/templates/sahm/updateMonitor.html
{% extends 'viewMonitor.html' %}

{% block content %}

<div class="info">
  <h2 class="page-header">Atualizar as Informações do Monitor</h2>
</div>

<!--<div class="info">
  <h1 class="page-header">Alterar Cadastro do Monitor</h1>
</div>-->

<form id="formCadCliente" data-toggle="validator" role="form" method="POST" action="{% url 'sahm:dados_cadastrais_monitor' %}">{% csrf_token %}

  <div class="row">
    <div class="form-group col-md-9">
      <label for="id_nome" class="control-label">Novo Nome:</label>
      <input type="text" name="nome" placeholder="Informe o seu nome completo" id="id_nome" class="form-control"/>
      <div class="help-block with-errors"></div>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-5">
      <label for="id_fone" class="control-label">Telefone:</label>
      <!--<input type="number" name="telefone" id="id_fone" class="form-control" placeholder="DDD+Número" required/>-->
      {{form_monitor.telefone}}
      <div class="help-block with-errors"></div>
    </div>

    <div class="form-group col-md-4">
      <label for="id_nascimento" class="control-label">Data de Nascimento:</label>
      <!--<input type="date" name="nascimento" id="id_nascimento" class="form-control" required/>-->
      {{form_monitor.nascimento}}
      <div class="help-block with-errors"></div>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-5">
        <label  for="id_curso" class="control-label">Curso:</label>
      <!--  <input type="text" name="curso" id="id_curso" class="form-control" required/>-->

          {% if user.monitor.curso == '1' %}
            <h4>CSHNB - ADMINISTRAÇÃO</h4>
          {% elif user.monitor.curso == '2' %}
            <h4>CSHNB - CIÊNCIAS BIOLÓGICAS</h4>
          {% elif user.monitor.curso == '3' %}
            <h4>CSHNB - ENFERMAGEM</h4>
          {% elif user.monitor.curso == '4' %}
            <h4>CSHNB - HISTÓRIA</h4>
          {% elif user.monitor.curso == '5' %}
            <h4>CSHNB - LETRAS</h4>
          {% elif user.monitor.curso == '6' %}
            <h4>CSHNB - MATEMÁTICA</h4>
          {% elif user.monitor.curso == '7' %}
            <h4>CSHNB - MEDICINA</h4>
          {% elif user.monitor.curso == '8' %}
            <h4>CSHNB - NUTRIÇÃO</h4>
          {% elif user.monitor.curso == '9' %}
            <h4>CSHNB - PEDAGOGIA</h4>
          {% elif user.monitor.curso == '10' %}
            <h4>CSHNB - SISTEMAS DE INFORMAÇÃO</h4>
          {% else %}
              {{form_monitor.curso}}
          {% endif%}

        <div class="help-block with-errors"></div>
    </div>

    <div class="form-group col-md-4">
      <label for="id_materia" class="control-label">Matéria</label>
      {{form_monitor.materia}}
    </div>
  </div>


{% if msg %}
  <h4>{{msg}}</h4>
{% else %}
  <div class="row" id="actions">
    <button type="submit" class="btn btn-primary">Alterar</button>
    <a href="{% url 'sahm:acesso_monitor' %}" class="btn btn-default">Cancelar</a>
  </div>
</form>
{% endif %}
{% endblock %}

sahm/templates/sahm/updatePassword.html
{% extends 'viewMonitor.html' %}

{% block content %}

<div class="info">
  <h3 class="page-header">Atualize sua Nova Senha</h3>
</div>

<form id="formUpdatePass" data-toggle="validator" role="form" method="POST" action="{% url 'sahm:update_password' %}">{% csrf_token %}

  <!--<div class="row">
    <div class="form-group col-md-4">
      <label class="control-label">Email antigo:</label>
      {{user.email}}
    </div>

    <div class="form_group col-md-4">
      <label for="email" class="control-label">Email novo:</label>
      {{form.email}}
    </div>
  </div>-

  <div class="row">
    <div class="form_group col-md-5">
      <label for="senha" class="control-label">Senha Atual:</label>
      <input type="password" name="senha_antiga" id="id_senha_atual" class="form-control" data-minlength="6" required/>
    </div>
  </div>

  <div class="row">

  </div>

  <div class="row">

    <div class="form_group col-md-5">
      <label for="id_senha" class="control-label">Nova Senha:</label>
      <input type="password" name="senha_atual" id="id_senha" class="form-control" data-minlength="6" required/>
    </div>

    <div class="form-group col-md-5">
      <label for="id_conf_senha" class="control-label">Confirme a Nova Senha:</label>
      <input type="password" name="confirmaSenha" id="id_conf_senha" class="form-control" data-match="#id_senha" data-match-error="As senhas não conferem!." required/>
      <div class="help-block with-errors"></div>
    </div>
  </div>-->

  {{form.as_p}}

  <div class="row" id="actions">
    <button type="submit" class="btn btn-primary">Atualizar</button>
    <a href="{% url 'sahm:dados_principal_monitor' %}" class="btn btn-default">Cancelar</a>
  </div>

</form>
{% endblock %}

sahm/templates/sahm/updateUserMonitor.html
{% extends 'viewMonitor.html' %}

{% block content %}

<div class="info">
  <h2 class="page-header">Principais Configurações do Monitor</h2>
</div>

<!--<div class="info">
  <h1 class="page-header">Alterar Cadastro do Monitor</h1>
</div>-->

<div class="row">
  <h3>Deseja alterar a sua senha?</h3>
  <a href="{% url 'sahm:update_password' %}">Alterar Senha</a>
</div>

<div class="row">
  <h3>Deseja alterar o seu email?</h3>
  <a href="{% url 'sahm:update_email' %}">Alterar Email</a>
</div>

<div class="row">
  <h3>Deseja excluir sua conta?</h3>
  <a href="{% url 'sahm:excluir_conta' %}" onclick="return confirm('Tem certeza que deseja excluir esta conta?')">Excluir Conta</a>
</div>

{% endblock %}